server:
  port: 8098


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8096/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: libro-docs
          uri: lb://libro
          predicates:
            - Path=/api/bibliotecaam/libro/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: libro
          uri: lb://libro
          predicates:
            - Path=/api/bibliotecaam/libro/**
        - id: donacion-docs
          uri: lb://microserviciodonacion
          predicates:
            - Path=/api/bibliotecaam/donacion/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: donacion
          uri: lb://microserviciodonacion
          predicates:
            - Path=/api/bibliotecaam/donacion/**
        - id: resenia-docs
          uri: lb://msresenia
          predicates:
            - Path=/api/bibliotecaam/resenia/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: resenia
          uri: lb://msresenia
          predicates:
            - Path=/api/bibliotecaam/resenia/**
        - id: asistencia-docs
          uri: lb://asistencia
          predicates:
            - Path=/api/bibliotecaam/asistencia/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: asistencia
          uri: lb://asistencia
          predicates:
            - Path=/api/bibliotecaam/asistencia/**
        - id: taller-docs
          uri: lb://taller
          predicates:
            - Path=/api/bibliotecaam/taller/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: taller
          uri: lb://taller
          predicates:
            - Path=/api/bibliotecaam/taller/**
        - id: usuario-docs
          uri: lb://usuario
          predicates:
            - Path=/api/bibliotecaam/usuario/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/api/bibliotecaam/usuario/**
        - id: compra-docs
          uri: lb://compra
          predicates:
            - Path=/api/bibliotecaam/compra/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: compra
          uri: lb://compra
          predicates:
            - Path=/api/bibliotecaam/compra/**
        - id: prestamo-docs
          uri: lb://prestamo
          predicates:
            - Path=/api/bibliotecaam/prestamo/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: prestamo
          uri: lb://prestamo
          predicates:
            - Path=/api/bibliotecaam/prestamo/**
        - id: empleado-docs
          uri: lb://empleado
          predicates:
            - Path=/api/bibliotecaam/empleado/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: empleado
          uri: lb://empleado
          predicates:
            - Path=/api/bibliotecaam/empleado/**
        - id: sancion-docs
          uri: lb://sancion
          predicates:
            - Path=/api/bibliotecaam/sancion/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: sancion
          uri: lb://sancion
          predicates:
            - Path=/api/bibliotecaam/sancion/**
        - id: auth-docs
          uri: lb://auth
          predicates:
            - Path=/api/bibliotecaam/auth/v3/api-docs/**
          filters:
            - StripPrefix=3
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/bibliotecaam/auth/**


management:
  endpoints:
    web:
        exposure:
          include: health, info, prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    urls:
      - name: Microservicio Libro
        url: /api/bibliotecaam/libro/v3/api-docs
      - name: Microservicio Donacion
        url: /api/bibliotecaam/donacion/v3/api-docs
      - name: Microservicio Usuario
        url: /api/bibliotecaam/usuario/v3/api-docs
      - name: Microservicio Prestamo
        url: /api/bibliotecaam/prestamo/v3/api-docs
      - name: Microservicio Sancion
        url: /api/bibliotecaam/sancion/v3/api-docs
      - name: Microservicio Resenia
        url: /api/bibliotecaam/resenia/v3/api-docs
      - name: Microservicio Empleado
        url: /api/bibliotecaam/empleado/v3/api-docs
      - name: Microservicio Taller
        url: /api/bibliotecaam/taller/v3/api-docs
      - name: Microservicio Asistencia
        url: /api/bibliotecaam/asistencia/v3/api-docs
      - name: Microservicio Compra
        url: /api/bibliotecaam/compra/v3/api-docs
      - name: Microservicio Seguridad
        url: /api/bibliotecaam/auth/v3/api-docs
    disable-swagger-default-url: true
  webjars:
    prefix: ""
  api-docs:
    enabled: true
  cache:
    disabled: true
  enable-native-support: true