server:
  port: 8098


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8096/eureka/

jwt:
  secret: 'YmlibGlvdGVjYWFtYmlibGlvdGVjYWFtYmlibGlvdGVjYWFtYmlibGlvdGVjYWFt'

spring:
  cloud:
    gateway:
      routes:
        - id: libro-docs
          uri: lb://libro
          predicates:
            - Path=/api/bibliotecaam/libro/**
            - Path=/api/bibliotecaam/libro/v3/api-docs/**
            - Path=/api/bibliotecaam/libro/swagger-ui/**
            - Path=/api/bibliotecaam/libro/swagger-ui.html
        - id: microserviciodonacion
          uri: lb://microserviciodonacion
          predicates:
            - Path=/api/bibliotecaam/donacion/**
        - id: msresenia
          uri: lb://msresenia
          predicates:
            - Path=/api/bibliotecaam/resenia/**
        - id: asistencia
          uri: lb://asistencia
          predicates:
            - Path=/api/bibliotecaam/asistencia/**
        - id: taller
          uri: lb://taller
          predicates:
            - Path=/api/bibliotecaam/taller/**
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/api/bibliotecaam/usuario/**
        - id: compra
          uri: lb://compra
          predicates:
            - Path=/api/bibliotecaam/compra/**
        - id: prestamo
          uri: lb://prestamo
          predicates:
            - Path=/api/bibliotecaam/prestamo/**
        - id: empleado
          uri: lb://empleado
          predicates:
            - Path=/api/bibliotecaam/empleado/**
        - id: security
          uri: lb://security
          predicates:
            - Path=/api/bibliotecaam/security/**
            - Path=/api/bibliotecaam/security/swagger-ui/**
            - Path=/api/bibliotecaam/security/swagger-ui.html
            - Path=/api/bibliotecaam/security/v3/api-docs/**
            - Path=/api/bibliotecaam/auth/**