server:
  port: 8100

spring:
  cloud:
    discovery:
      enabled: true

springdoc:
  servers:
    - uri: http://localhost:8098/api/bibiliotecaam/auth
      description: Via del Api Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8096/eureka/
