server:
  port: 8084

spring:
  cloud:
    discovery:
      enabled: true

springdoc:
  servers:
    - url: http://localhost:8098/api/bibliotecaam/empleado
      description: Via del Api Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8096/eureka/